// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiWomiu5df-pm6gwOJSLGSXJ2rMcSgMMM',
    appId: '1:151210588565:web:9612d3c9d18d0e210a5e9c',
    messagingSenderId: '151210588565',
    projectId: 'beenedeek-19505',
    authDomain: 'beenedeek-19505.firebaseapp.com',
    storageBucket: 'beenedeek-19505.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTpkRfEXo9EFlUvIUItG1tlXENCjPrihU',
    appId: '1:151210588565:android:5e66adf7a6eda0570a5e9c',
    messagingSenderId: '151210588565',
    projectId: 'beenedeek-19505',
    storageBucket: 'beenedeek-19505.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa6WmTNvPTsH4-rkRAiH7FQvTTwstPoGg',
    appId: '1:151210588565:ios:6f8d886d47879f910a5e9c',
    messagingSenderId: '151210588565',
    projectId: 'beenedeek-19505',
    storageBucket: 'beenedeek-19505.firebasestorage.app',
    androidClientId: '151210588565-idt8mprliv7vuibalf93kv06a7l90g0a.apps.googleusercontent.com',
    iosBundleId: 'com.m3tech.beenEdeekPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa6WmTNvPTsH4-rkRAiH7FQvTTwstPoGg',
    appId: '1:151210588565:ios:6f8d886d47879f910a5e9c',
    messagingSenderId: '151210588565',
    projectId: 'beenedeek-19505',
    storageBucket: 'beenedeek-19505.firebasestorage.app',
    androidClientId: '151210588565-idt8mprliv7vuibalf93kv06a7l90g0a.apps.googleusercontent.com',
    iosBundleId: 'com.m3tech.beenEdeekPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiWomiu5df-pm6gwOJSLGSXJ2rMcSgMMM',
    appId: '1:151210588565:web:5a9c9975fc9c23c20a5e9c',
    messagingSenderId: '151210588565',
    projectId: 'beenedeek-19505',
    authDomain: 'beenedeek-19505.firebaseapp.com',
    storageBucket: 'beenedeek-19505.firebasestorage.app',
  );

}